export const PROPERTIES_FETCHED = 'PROPERTIES_FETCHED';
export const FETCHPROPERTY_REQUEST = 'FETCH_PROPERTY_REQUEST';
export const FETCHPROPERTY_FAILURE = 'FETCH_PROPERTY_FAILURE';
export const ADD_TO_SAVED = 'ADD_TO_SAVED';
export const REMOVE_FROM_SAVED = 'REMOVE_FROM_SAVED';
